'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UploadRasterImage

	'''<summary>
	'''ServerSideForm control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents ServerSideForm As Global.System.Web.UI.HtmlControls.HtmlForm

	'''<summary>
	'''RasterImageUploader control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RasterImageUploader As Global.System.Web.UI.WebControls.FileUpload

	'''<summary>
	'''PerformUploadButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents PerformUploadButton As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''StatusLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents StatusLabel As Global.System.Web.UI.WebControls.Label
End Class
